/// Curated pool of well-known, encouraging verses used for Verse of the Day
/// and (Phase 4) lock-screen wallpapers. References use the standard
/// 1..66 book numbering (Genesis = 1, Revelation = 66).
library;

enum VerseTheme { comfort, strength, hope, love, faith, peace, wisdom, praise }

class PoolVerse {
  const PoolVerse(
    this.bookId,
    this.chapter,
    this.verse,
    this.theme, {
    this.endVerse,
  });

  final int bookId;
  final int chapter;
  final int verse;

  /// Inclusive last verse when the quote spans multiple verses.
  final int? endVerse;
  final VerseTheme theme;

  bool get isRange => endVerse != null && endVerse! > verse;
}

// Book ids used below.
const _gen = 1, _exo = 2, _num = 4, _deu = 5, _jos = 6, _sa1 = 9, _sa2 = 10;
const _ch1 = 13;
const _neh = 16, _job = 18, _psa = 19, _pro = 20, _ecc = 21, _isa = 23;
const _jer = 24, _lam = 25, _joe = 29, _mic = 33, _nah = 34, _hab = 35;
const _zep = 36, _mal = 39;
const _mat = 40, _mar = 41, _luk = 42, _joh = 43, _act = 44, _rom = 45;
const _co1 = 46, _co2 = 47, _gal = 48, _eph = 49, _phi = 50, _col = 51;
const _th1 = 52, _th2 = 53, _ti1 = 54, _ti2 = 55, _tit = 56, _heb = 58;
const _jam = 59, _pe1 = 60, _pe2 = 61, _jo1 = 62, _jud = 65, _rev = 66;

const List<PoolVerse> versePool = [
  // ── Comfort ──────────────────────────────────────────────────────────────
  PoolVerse(_psa, 23, 1, VerseTheme.comfort),
  PoolVerse(_psa, 23, 4, VerseTheme.comfort),
  PoolVerse(_psa, 34, 18, VerseTheme.comfort),
  PoolVerse(_psa, 46, 1, VerseTheme.comfort),
  PoolVerse(_psa, 55, 22, VerseTheme.comfort),
  PoolVerse(_psa, 73, 26, VerseTheme.comfort),
  PoolVerse(_psa, 91, 1, VerseTheme.comfort, endVerse: 2),
  PoolVerse(_psa, 94, 19, VerseTheme.comfort),
  PoolVerse(_psa, 119, 50, VerseTheme.comfort),
  PoolVerse(_psa, 119, 76, VerseTheme.comfort),
  PoolVerse(_psa, 145, 18, VerseTheme.comfort),
  PoolVerse(_psa, 147, 3, VerseTheme.comfort),
  PoolVerse(_isa, 41, 10, VerseTheme.comfort),
  PoolVerse(_isa, 41, 13, VerseTheme.comfort),
  PoolVerse(_isa, 43, 2, VerseTheme.comfort),
  PoolVerse(_isa, 49, 13, VerseTheme.comfort),
  PoolVerse(_isa, 51, 12, VerseTheme.comfort),
  PoolVerse(_isa, 61, 1, VerseTheme.comfort),
  PoolVerse(_isa, 66, 13, VerseTheme.comfort),
  PoolVerse(_lam, 3, 22, VerseTheme.comfort, endVerse: 23),
  PoolVerse(_mat, 5, 4, VerseTheme.comfort),
  PoolVerse(_mat, 11, 28, VerseTheme.comfort, endVerse: 30),
  PoolVerse(_joh, 14, 1, VerseTheme.comfort),
  PoolVerse(_joh, 14, 18, VerseTheme.comfort),
  PoolVerse(_joh, 16, 33, VerseTheme.comfort),
  PoolVerse(_co2, 1, 3, VerseTheme.comfort, endVerse: 4),
  PoolVerse(_th2, 2, 16, VerseTheme.comfort, endVerse: 17),
  PoolVerse(_pe1, 5, 7, VerseTheme.comfort),
  PoolVerse(_rev, 21, 4, VerseTheme.comfort),
  PoolVerse(_deu, 33, 27, VerseTheme.comfort),
  PoolVerse(_nah, 1, 7, VerseTheme.comfort),
  PoolVerse(_zep, 3, 17, VerseTheme.comfort),

  // ── Strength ─────────────────────────────────────────────────────────────
  PoolVerse(_exo, 15, 2, VerseTheme.strength),
  PoolVerse(_deu, 31, 6, VerseTheme.strength),
  PoolVerse(_deu, 31, 8, VerseTheme.strength),
  PoolVerse(_jos, 1, 9, VerseTheme.strength),
  PoolVerse(_sa1, 17, 47, VerseTheme.strength),
  PoolVerse(_ch1, 16, 11, VerseTheme.strength),
  PoolVerse(_neh, 8, 10, VerseTheme.strength),
  PoolVerse(_psa, 18, 2, VerseTheme.strength),
  PoolVerse(_psa, 18, 32, VerseTheme.strength),
  PoolVerse(_psa, 27, 1, VerseTheme.strength),
  PoolVerse(_psa, 28, 7, VerseTheme.strength),
  PoolVerse(_psa, 29, 11, VerseTheme.strength),
  PoolVerse(_psa, 31, 24, VerseTheme.strength),
  PoolVerse(_psa, 46, 10, VerseTheme.strength),
  PoolVerse(_psa, 59, 16, VerseTheme.strength),
  PoolVerse(_psa, 62, 6, VerseTheme.strength),
  PoolVerse(_psa, 118, 14, VerseTheme.strength),
  PoolVerse(_psa, 121, 1, VerseTheme.strength, endVerse: 2),
  PoolVerse(_psa, 138, 3, VerseTheme.strength),
  PoolVerse(_isa, 12, 2, VerseTheme.strength),
  PoolVerse(_isa, 26, 4, VerseTheme.strength),
  PoolVerse(_isa, 35, 4, VerseTheme.strength),
  PoolVerse(_isa, 40, 29, VerseTheme.strength),
  PoolVerse(_isa, 40, 31, VerseTheme.strength),
  PoolVerse(_isa, 54, 17, VerseTheme.strength),
  PoolVerse(_hab, 3, 19, VerseTheme.strength),
  PoolVerse(_mar, 9, 23, VerseTheme.strength),
  PoolVerse(_mar, 10, 27, VerseTheme.strength),
  PoolVerse(_luk, 1, 37, VerseTheme.strength),
  PoolVerse(_co1, 16, 13, VerseTheme.strength),
  PoolVerse(_co2, 4, 16, VerseTheme.strength),
  PoolVerse(_co2, 12, 9, VerseTheme.strength),
  PoolVerse(_eph, 3, 16, VerseTheme.strength),
  PoolVerse(_eph, 6, 10, VerseTheme.strength),
  PoolVerse(_phi, 4, 13, VerseTheme.strength),
  PoolVerse(_col, 1, 11, VerseTheme.strength),
  PoolVerse(_ti2, 1, 7, VerseTheme.strength),
  PoolVerse(_heb, 13, 6, VerseTheme.strength),
  PoolVerse(_jo1, 4, 4, VerseTheme.strength),

  // ── Hope ─────────────────────────────────────────────────────────────────
  PoolVerse(_job, 11, 18, VerseTheme.hope),
  PoolVerse(_psa, 25, 5, VerseTheme.hope),
  PoolVerse(_psa, 30, 5, VerseTheme.hope),
  PoolVerse(_psa, 33, 18, VerseTheme.hope),
  PoolVerse(_psa, 33, 22, VerseTheme.hope),
  PoolVerse(_psa, 39, 7, VerseTheme.hope),
  PoolVerse(_psa, 42, 11, VerseTheme.hope),
  PoolVerse(_psa, 62, 5, VerseTheme.hope),
  PoolVerse(_psa, 71, 5, VerseTheme.hope),
  PoolVerse(_psa, 119, 114, VerseTheme.hope),
  PoolVerse(_psa, 130, 5, VerseTheme.hope),
  PoolVerse(_psa, 146, 5, VerseTheme.hope),
  PoolVerse(_pro, 23, 18, VerseTheme.hope),
  PoolVerse(_pro, 24, 14, VerseTheme.hope),
  PoolVerse(_isa, 40, 8, VerseTheme.hope),
  PoolVerse(_jer, 17, 7, VerseTheme.hope),
  PoolVerse(_jer, 29, 11, VerseTheme.hope),
  PoolVerse(_jer, 31, 17, VerseTheme.hope),
  PoolVerse(_lam, 3, 24, VerseTheme.hope),
  PoolVerse(_lam, 3, 25, VerseTheme.hope),
  PoolVerse(_joe, 2, 25, VerseTheme.hope),
  PoolVerse(_mic, 7, 7, VerseTheme.hope),
  PoolVerse(_rom, 5, 5, VerseTheme.hope),
  PoolVerse(_rom, 8, 24, VerseTheme.hope, endVerse: 25),
  PoolVerse(_rom, 8, 28, VerseTheme.hope),
  PoolVerse(_rom, 12, 12, VerseTheme.hope),
  PoolVerse(_rom, 15, 4, VerseTheme.hope),
  PoolVerse(_rom, 15, 13, VerseTheme.hope),
  PoolVerse(_co1, 13, 13, VerseTheme.hope),
  PoolVerse(_co2, 4, 17, VerseTheme.hope, endVerse: 18),
  PoolVerse(_eph, 1, 18, VerseTheme.hope),
  PoolVerse(_col, 1, 27, VerseTheme.hope),
  PoolVerse(_tit, 2, 13, VerseTheme.hope),
  PoolVerse(_heb, 6, 19, VerseTheme.hope),
  PoolVerse(_heb, 10, 23, VerseTheme.hope),
  PoolVerse(_heb, 11, 1, VerseTheme.hope),
  PoolVerse(_pe1, 1, 3, VerseTheme.hope),
  PoolVerse(_pe1, 1, 13, VerseTheme.hope),
  PoolVerse(_rev, 22, 5, VerseTheme.hope),

  // ── Love ─────────────────────────────────────────────────────────────────
  PoolVerse(_deu, 6, 5, VerseTheme.love),
  PoolVerse(_deu, 7, 9, VerseTheme.love),
  PoolVerse(_psa, 36, 7, VerseTheme.love),
  PoolVerse(_psa, 86, 15, VerseTheme.love),
  PoolVerse(_psa, 103, 8, VerseTheme.love),
  PoolVerse(_psa, 103, 11, VerseTheme.love, endVerse: 12),
  PoolVerse(_psa, 136, 1, VerseTheme.love),
  PoolVerse(_pro, 3, 3, VerseTheme.love),
  PoolVerse(_pro, 10, 12, VerseTheme.love),
  PoolVerse(_pro, 17, 17, VerseTheme.love),
  PoolVerse(_isa, 54, 10, VerseTheme.love),
  PoolVerse(_jer, 31, 3, VerseTheme.love),
  PoolVerse(_mat, 5, 44, VerseTheme.love),
  PoolVerse(_mat, 22, 37, VerseTheme.love, endVerse: 39),
  PoolVerse(_mar, 12, 30, VerseTheme.love, endVerse: 31),
  PoolVerse(_luk, 6, 35, VerseTheme.love),
  PoolVerse(_joh, 3, 16, VerseTheme.love),
  PoolVerse(_joh, 13, 34, VerseTheme.love, endVerse: 35),
  PoolVerse(_joh, 15, 9, VerseTheme.love),
  PoolVerse(_joh, 15, 12, VerseTheme.love, endVerse: 13),
  PoolVerse(_rom, 5, 8, VerseTheme.love),
  PoolVerse(_rom, 8, 38, VerseTheme.love, endVerse: 39),
  PoolVerse(_rom, 12, 9, VerseTheme.love, endVerse: 10),
  PoolVerse(_rom, 13, 8, VerseTheme.love),
  PoolVerse(_co1, 13, 4, VerseTheme.love, endVerse: 7),
  PoolVerse(_co1, 16, 14, VerseTheme.love),
  PoolVerse(_gal, 5, 13, VerseTheme.love),
  PoolVerse(_gal, 5, 22, VerseTheme.love, endVerse: 23),
  PoolVerse(_eph, 2, 4, VerseTheme.love, endVerse: 5),
  PoolVerse(_eph, 3, 17, VerseTheme.love, endVerse: 19),
  PoolVerse(_eph, 4, 2, VerseTheme.love),
  PoolVerse(_eph, 5, 2, VerseTheme.love),
  PoolVerse(_col, 3, 14, VerseTheme.love),
  PoolVerse(_th1, 3, 12, VerseTheme.love),
  PoolVerse(_pe1, 4, 8, VerseTheme.love),
  PoolVerse(_jo1, 3, 1, VerseTheme.love),
  PoolVerse(_jo1, 3, 18, VerseTheme.love),
  PoolVerse(_jo1, 4, 7, VerseTheme.love, endVerse: 8),
  PoolVerse(_jo1, 4, 10, VerseTheme.love),
  PoolVerse(_jo1, 4, 16, VerseTheme.love),
  PoolVerse(_jo1, 4, 18, VerseTheme.love),
  PoolVerse(_jo1, 4, 19, VerseTheme.love),
  PoolVerse(_jud, 1, 21, VerseTheme.love),

  // ── Faith ────────────────────────────────────────────────────────────────
  PoolVerse(_gen, 15, 6, VerseTheme.faith),
  PoolVerse(_num, 23, 19, VerseTheme.faith),
  PoolVerse(_sa2, 22, 31, VerseTheme.faith),
  PoolVerse(_psa, 9, 10, VerseTheme.faith),
  PoolVerse(_psa, 20, 7, VerseTheme.faith),
  PoolVerse(_psa, 37, 5, VerseTheme.faith),
  PoolVerse(_psa, 56, 3, VerseTheme.faith),
  PoolVerse(_psa, 84, 12, VerseTheme.faith),
  PoolVerse(_psa, 112, 7, VerseTheme.faith),
  PoolVerse(_psa, 125, 1, VerseTheme.faith),
  PoolVerse(_pro, 3, 5, VerseTheme.faith, endVerse: 6),
  PoolVerse(_pro, 29, 25, VerseTheme.faith),
  PoolVerse(_pro, 30, 5, VerseTheme.faith),
  PoolVerse(_isa, 7, 9, VerseTheme.faith),
  PoolVerse(_isa, 30, 15, VerseTheme.faith),
  PoolVerse(_hab, 2, 4, VerseTheme.faith),
  PoolVerse(_mat, 6, 33, VerseTheme.faith),
  PoolVerse(_mat, 7, 7, VerseTheme.faith, endVerse: 8),
  PoolVerse(_mat, 9, 22, VerseTheme.faith),
  PoolVerse(_mat, 17, 20, VerseTheme.faith),
  PoolVerse(_mat, 21, 22, VerseTheme.faith),
  PoolVerse(_mar, 5, 36, VerseTheme.faith),
  PoolVerse(_mar, 11, 24, VerseTheme.faith),
  PoolVerse(_luk, 17, 6, VerseTheme.faith),
  PoolVerse(_joh, 6, 35, VerseTheme.faith),
  PoolVerse(_joh, 11, 25, VerseTheme.faith, endVerse: 26),
  PoolVerse(_joh, 20, 29, VerseTheme.faith),
  PoolVerse(_act, 16, 31, VerseTheme.faith),
  PoolVerse(_rom, 1, 17, VerseTheme.faith),
  PoolVerse(_rom, 4, 20, VerseTheme.faith, endVerse: 21),
  PoolVerse(_rom, 10, 9, VerseTheme.faith, endVerse: 10),
  PoolVerse(_rom, 10, 17, VerseTheme.faith),
  PoolVerse(_co2, 5, 7, VerseTheme.faith),
  PoolVerse(_gal, 2, 20, VerseTheme.faith),
  PoolVerse(_gal, 3, 26, VerseTheme.faith),
  PoolVerse(_eph, 2, 8, VerseTheme.faith, endVerse: 9),
  PoolVerse(_eph, 6, 16, VerseTheme.faith),
  PoolVerse(_ti1, 6, 12, VerseTheme.faith),
  PoolVerse(_ti2, 4, 7, VerseTheme.faith),
  PoolVerse(_heb, 11, 6, VerseTheme.faith),
  PoolVerse(_heb, 12, 1, VerseTheme.faith, endVerse: 2),
  PoolVerse(_jam, 1, 6, VerseTheme.faith),
  PoolVerse(_jam, 2, 17, VerseTheme.faith),
  PoolVerse(_pe1, 1, 8, VerseTheme.faith, endVerse: 9),
  PoolVerse(_jo1, 5, 4, VerseTheme.faith),

  // ── Peace ────────────────────────────────────────────────────────────────
  PoolVerse(_num, 6, 24, VerseTheme.peace, endVerse: 26),
  PoolVerse(_psa, 4, 8, VerseTheme.peace),
  PoolVerse(_psa, 34, 14, VerseTheme.peace),
  PoolVerse(_psa, 85, 8, VerseTheme.peace),
  PoolVerse(_psa, 119, 165, VerseTheme.peace),
  PoolVerse(_pro, 12, 20, VerseTheme.peace),
  PoolVerse(_pro, 14, 30, VerseTheme.peace),
  PoolVerse(_pro, 16, 7, VerseTheme.peace),
  PoolVerse(_isa, 9, 6, VerseTheme.peace),
  PoolVerse(_isa, 26, 3, VerseTheme.peace),
  PoolVerse(_isa, 32, 17, VerseTheme.peace),
  PoolVerse(_isa, 54, 13, VerseTheme.peace),
  PoolVerse(_isa, 55, 12, VerseTheme.peace),
  PoolVerse(_mat, 5, 9, VerseTheme.peace),
  PoolVerse(_mar, 4, 39, VerseTheme.peace),
  PoolVerse(_luk, 2, 14, VerseTheme.peace),
  PoolVerse(_joh, 14, 27, VerseTheme.peace),
  PoolVerse(_joh, 20, 19, VerseTheme.peace),
  PoolVerse(_rom, 5, 1, VerseTheme.peace),
  PoolVerse(_rom, 8, 6, VerseTheme.peace),
  PoolVerse(_rom, 12, 18, VerseTheme.peace),
  PoolVerse(_rom, 14, 17, VerseTheme.peace),
  PoolVerse(_rom, 14, 19, VerseTheme.peace),
  PoolVerse(_rom, 15, 33, VerseTheme.peace),
  PoolVerse(_co1, 14, 33, VerseTheme.peace),
  PoolVerse(_co2, 13, 11, VerseTheme.peace),
  PoolVerse(_eph, 2, 14, VerseTheme.peace),
  PoolVerse(_phi, 4, 6, VerseTheme.peace, endVerse: 7),
  PoolVerse(_phi, 4, 9, VerseTheme.peace),
  PoolVerse(_col, 3, 15, VerseTheme.peace),
  PoolVerse(_th2, 3, 16, VerseTheme.peace),
  PoolVerse(_heb, 12, 14, VerseTheme.peace),
  PoolVerse(_jam, 3, 17, VerseTheme.peace, endVerse: 18),
  PoolVerse(_pe1, 3, 11, VerseTheme.peace),
  PoolVerse(_pe2, 1, 2, VerseTheme.peace),

  // ── Wisdom ───────────────────────────────────────────────────────────────
  PoolVerse(_deu, 30, 19, VerseTheme.wisdom),
  PoolVerse(_job, 12, 13, VerseTheme.wisdom),
  PoolVerse(_job, 28, 28, VerseTheme.wisdom),
  PoolVerse(_psa, 1, 1, VerseTheme.wisdom, endVerse: 2),
  PoolVerse(_psa, 19, 7, VerseTheme.wisdom),
  PoolVerse(_psa, 32, 8, VerseTheme.wisdom),
  PoolVerse(_psa, 37, 23, VerseTheme.wisdom),
  PoolVerse(_psa, 90, 12, VerseTheme.wisdom),
  PoolVerse(_psa, 111, 10, VerseTheme.wisdom),
  PoolVerse(_psa, 119, 9, VerseTheme.wisdom),
  PoolVerse(_psa, 119, 11, VerseTheme.wisdom),
  PoolVerse(_psa, 119, 105, VerseTheme.wisdom),
  PoolVerse(_psa, 119, 130, VerseTheme.wisdom),
  PoolVerse(_pro, 1, 7, VerseTheme.wisdom),
  PoolVerse(_pro, 2, 6, VerseTheme.wisdom),
  PoolVerse(_pro, 3, 7, VerseTheme.wisdom),
  PoolVerse(_pro, 3, 13, VerseTheme.wisdom),
  PoolVerse(_pro, 4, 7, VerseTheme.wisdom),
  PoolVerse(_pro, 4, 23, VerseTheme.wisdom),
  PoolVerse(_pro, 9, 10, VerseTheme.wisdom),
  PoolVerse(_pro, 11, 2, VerseTheme.wisdom),
  PoolVerse(_pro, 12, 15, VerseTheme.wisdom),
  PoolVerse(_pro, 13, 20, VerseTheme.wisdom),
  PoolVerse(_pro, 15, 1, VerseTheme.wisdom),
  PoolVerse(_pro, 16, 3, VerseTheme.wisdom),
  PoolVerse(_pro, 16, 9, VerseTheme.wisdom),
  PoolVerse(_pro, 16, 16, VerseTheme.wisdom),
  PoolVerse(_pro, 17, 27, VerseTheme.wisdom),
  PoolVerse(_pro, 18, 15, VerseTheme.wisdom),
  PoolVerse(_pro, 19, 20, VerseTheme.wisdom),
  PoolVerse(_pro, 19, 21, VerseTheme.wisdom),
  PoolVerse(_pro, 22, 6, VerseTheme.wisdom),
  PoolVerse(_pro, 27, 17, VerseTheme.wisdom),
  PoolVerse(_ecc, 3, 1, VerseTheme.wisdom),
  PoolVerse(_ecc, 3, 11, VerseTheme.wisdom),
  PoolVerse(_ecc, 7, 12, VerseTheme.wisdom),
  PoolVerse(_ecc, 12, 13, VerseTheme.wisdom),
  PoolVerse(_isa, 55, 8, VerseTheme.wisdom, endVerse: 9),
  PoolVerse(_mic, 6, 8, VerseTheme.wisdom),
  PoolVerse(_mat, 5, 16, VerseTheme.wisdom),
  PoolVerse(_mat, 6, 34, VerseTheme.wisdom),
  PoolVerse(_mat, 7, 12, VerseTheme.wisdom),
  PoolVerse(_mat, 7, 24, VerseTheme.wisdom),
  PoolVerse(_luk, 6, 31, VerseTheme.wisdom),
  PoolVerse(_joh, 8, 12, VerseTheme.wisdom),
  PoolVerse(_joh, 8, 32, VerseTheme.wisdom),
  PoolVerse(_rom, 12, 2, VerseTheme.wisdom),
  PoolVerse(_co1, 10, 31, VerseTheme.wisdom),
  PoolVerse(_gal, 6, 9, VerseTheme.wisdom),
  PoolVerse(_eph, 4, 32, VerseTheme.wisdom),
  PoolVerse(_eph, 5, 15, VerseTheme.wisdom, endVerse: 16),
  PoolVerse(_phi, 2, 3, VerseTheme.wisdom, endVerse: 4),
  PoolVerse(_phi, 4, 8, VerseTheme.wisdom),
  PoolVerse(_col, 3, 2, VerseTheme.wisdom),
  PoolVerse(_col, 3, 23, VerseTheme.wisdom),
  PoolVerse(_col, 4, 6, VerseTheme.wisdom),
  PoolVerse(_ti2, 3, 16, VerseTheme.wisdom, endVerse: 17),
  PoolVerse(_heb, 4, 12, VerseTheme.wisdom),
  PoolVerse(_jam, 1, 5, VerseTheme.wisdom),
  PoolVerse(_jam, 1, 19, VerseTheme.wisdom),
  PoolVerse(_jam, 1, 22, VerseTheme.wisdom),
  PoolVerse(_jam, 3, 13, VerseTheme.wisdom),
  PoolVerse(_jam, 4, 10, VerseTheme.wisdom),
  PoolVerse(_pe2, 3, 18, VerseTheme.wisdom),

  // ── Praise ───────────────────────────────────────────────────────────────
  PoolVerse(_gen, 1, 1, VerseTheme.praise),
  PoolVerse(_exo, 15, 11, VerseTheme.praise),
  PoolVerse(_ch1, 16, 34, VerseTheme.praise),
  PoolVerse(_ch1, 29, 11, VerseTheme.praise),
  PoolVerse(_psa, 8, 1, VerseTheme.praise),
  PoolVerse(_psa, 9, 1, VerseTheme.praise),
  PoolVerse(_psa, 16, 11, VerseTheme.praise),
  PoolVerse(_psa, 19, 1, VerseTheme.praise),
  PoolVerse(_psa, 19, 14, VerseTheme.praise),
  PoolVerse(_psa, 24, 1, VerseTheme.praise),
  PoolVerse(_psa, 34, 1, VerseTheme.praise),
  PoolVerse(_psa, 34, 8, VerseTheme.praise),
  PoolVerse(_psa, 47, 1, VerseTheme.praise),
  PoolVerse(_psa, 48, 1, VerseTheme.praise),
  PoolVerse(_psa, 63, 3, VerseTheme.praise, endVerse: 4),
  PoolVerse(_psa, 66, 1, VerseTheme.praise, endVerse: 2),
  PoolVerse(_psa, 86, 12, VerseTheme.praise),
  PoolVerse(_psa, 95, 1, VerseTheme.praise, endVerse: 2),
  PoolVerse(_psa, 96, 1, VerseTheme.praise, endVerse: 2),
  PoolVerse(_psa, 100, 1, VerseTheme.praise, endVerse: 2),
  PoolVerse(_psa, 100, 4, VerseTheme.praise, endVerse: 5),
  PoolVerse(_psa, 103, 1, VerseTheme.praise, endVerse: 2),
  PoolVerse(_psa, 104, 33, VerseTheme.praise),
  PoolVerse(_psa, 105, 1, VerseTheme.praise, endVerse: 2),
  PoolVerse(_psa, 106, 1, VerseTheme.praise),
  PoolVerse(_psa, 107, 1, VerseTheme.praise),
  PoolVerse(_psa, 113, 3, VerseTheme.praise),
  PoolVerse(_psa, 117, 1, VerseTheme.praise, endVerse: 2),
  PoolVerse(_psa, 118, 24, VerseTheme.praise),
  PoolVerse(_psa, 139, 14, VerseTheme.praise),
  PoolVerse(_psa, 145, 3, VerseTheme.praise),
  PoolVerse(_psa, 147, 1, VerseTheme.praise),
  PoolVerse(_psa, 150, 6, VerseTheme.praise),
  PoolVerse(_isa, 6, 3, VerseTheme.praise),
  PoolVerse(_isa, 25, 1, VerseTheme.praise),
  PoolVerse(_isa, 40, 28, VerseTheme.praise),
  PoolVerse(_isa, 42, 10, VerseTheme.praise),
  PoolVerse(_mal, 3, 6, VerseTheme.praise),
  PoolVerse(_luk, 1, 46, VerseTheme.praise, endVerse: 47),
  PoolVerse(_rom, 11, 33, VerseTheme.praise),
  PoolVerse(_rom, 11, 36, VerseTheme.praise),
  PoolVerse(_eph, 1, 3, VerseTheme.praise),
  PoolVerse(_eph, 3, 20, VerseTheme.praise, endVerse: 21),
  PoolVerse(_phi, 4, 4, VerseTheme.praise),
  PoolVerse(_col, 3, 16, VerseTheme.praise),
  PoolVerse(_th1, 5, 16, VerseTheme.praise, endVerse: 18),
  PoolVerse(_heb, 13, 8, VerseTheme.praise),
  PoolVerse(_heb, 13, 15, VerseTheme.praise),
  PoolVerse(_jam, 1, 17, VerseTheme.praise),
  PoolVerse(_pe1, 2, 9, VerseTheme.praise),
  PoolVerse(_rev, 4, 8, VerseTheme.praise),
  PoolVerse(_rev, 4, 11, VerseTheme.praise),
  PoolVerse(_rev, 5, 12, VerseTheme.praise),
  PoolVerse(_rev, 7, 12, VerseTheme.praise),
  PoolVerse(_rev, 19, 6, VerseTheme.praise),
];
