//go:build ignore
// +build ignore

package filestore
package filestore

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/melion/fullstack-bible/backend/internal/domain"
	"github.com/melion/fullstack-bible/backend/internal/service"





























































































































































































































































































































}	return bucket	}		items[userID] = bucket		bucket = map[string]T{}	if !ok {	bucket, ok := items[userID]func ensureBucket[T any](items map[string]map[string]T, userID string) map[string]T {}	return domain.User{}, false	}		}			return user, true		if strings.EqualFold(user.Email, email) {	for _, user := range r.data.Users {func (r *Repository) findUserByEmailLocked(email string) (domain.User, bool) {}	return item	bucket[item.Translation] = item	item.UserID = userID	}		return current	if current, ok := bucket[item.Translation]; ok && current.UpdatedAt.After(item.UpdatedAt) {	bucket := ensureBucket(r.data.ReadingPositions, userID)func (r *Repository) upsertReadingPositionLocked(userID string, item domain.ReadingPosition) domain.ReadingPosition {}	return item	bucket[item.ID] = item	item.UserID = userID	}		return current	if current, ok := bucket[item.ID]; ok && current.UpdatedAt.After(item.UpdatedAt) {	bucket := ensureBucket(r.data.Bookmarks, userID)func (r *Repository) upsertBookmarkLocked(userID string, item domain.Bookmark) domain.Bookmark {}	return item	bucket[item.ID] = item	item.UserID = userID	}		return current	if current, ok := bucket[item.ID]; ok && current.UpdatedAt.After(item.UpdatedAt) {	bucket := ensureBucket(r.data.Highlights, userID)func (r *Repository) upsertHighlightLocked(userID string, item domain.Highlight) domain.Highlight {}	return item	bucket[item.ID] = item	item.UserID = userID	}		return current	if current, ok := bucket[item.ID]; ok && current.UpdatedAt.After(item.UpdatedAt) {	bucket := ensureBucket(r.data.Notes, userID)func (r *Repository) upsertNoteLocked(userID string, item domain.Note) domain.Note {}	}		ServerTime:       time.Now().UTC(),		ReadingPositions: sortedValues(ensureBucket(r.data.ReadingPositions, user.ID), func(a, b domain.ReadingPosition) bool { return a.UpdatedAt.After(b.UpdatedAt) }),		Bookmarks:        sortedValues(ensureBucket(r.data.Bookmarks, user.ID), func(a, b domain.Bookmark) bool { return a.UpdatedAt.After(b.UpdatedAt) }),		Highlights:       sortedValues(ensureBucket(r.data.Highlights, user.ID), func(a, b domain.Highlight) bool { return a.UpdatedAt.After(b.UpdatedAt) }),		Notes:            sortedValues(ensureBucket(r.data.Notes, user.ID), func(a, b domain.Note) bool { return a.UpdatedAt.After(b.UpdatedAt) }),		User:             user,	return domain.SyncSnapshot{func (r *Repository) snapshotLocked(user domain.User) domain.SyncSnapshot {}	return os.WriteFile(r.path, bytes, 0o644)	}		return err	if err != nil {	bytes, err := json.MarshalIndent(r.data, "", "  ")func (r *Repository) saveLocked() error {}	}		ReadingPositions: map[string]map[string]domain.ReadingPosition{},		Bookmarks:        map[string]map[string]domain.Bookmark{},		Highlights:       map[string]map[string]domain.Highlight{},		Notes:            map[string]map[string]domain.Note{},		Users:            map[string]domain.User{},	return state{func newState() state {}	}		r.data.ReadingPositions = map[string]map[string]domain.ReadingPosition{}	if r.data.ReadingPositions == nil {	}		r.data.Bookmarks = map[string]map[string]domain.Bookmark{}	if r.data.Bookmarks == nil {	}		r.data.Highlights = map[string]map[string]domain.Highlight{}	if r.data.Highlights == nil {	}		r.data.Notes = map[string]map[string]domain.Note{}	if r.data.Notes == nil {	}		return		r.data = newState()	if r.data.Users == nil {func (r *Repository) normalize() {}	return nil	r.normalize()	}		return err	if err := json.Unmarshal(bytes, &r.data); err != nil {	}		return nil	if len(bytes) == 0 {	}		return err	if err != nil {	}		return r.saveLocked()	if errors.Is(err, os.ErrNotExist) {	bytes, err := os.ReadFile(r.path)	}		return err	if err := os.MkdirAll(filepath.Dir(r.path), 0o755); err != nil {func (r *Repository) load() error {}	return out, nil	}		out = out[:limit]	if len(out) > limit {	sort.Slice(out, func(i, j int) bool { return out[i].UpdatedAt.After(out[j].UpdatedAt) })	}		}			out = append(out, item)		if strings.Contains(strings.ToLower(item.Body), query) {		}			continue		if item.DeletedAt != nil {	for _, item := range bucket {	out := make([]domain.Note, 0, len(bucket))	bucket := ensureBucket(r.data.Notes, userID)	}		return []domain.Note{}, nil	if query == "" {	query = strings.ToLower(strings.TrimSpace(query))	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) SearchNotes(userID, query string, limit int) ([]domain.Note, error) {}	return out, r.saveLocked()	out := r.upsertReadingPositionLocked(userID, item)	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) UpsertReadingPosition(userID string, item domain.ReadingPosition) (domain.ReadingPosition, error) {}	return r.saveLocked()	bucket[id] = item	item.UpdatedAt = now	item.DeletedAt = &now	item.UserID = userID	now := time.Now().UTC()	}		return service.ErrNotFound	if !ok {	item, ok := bucket[id]	bucket := ensureBucket(r.data.Bookmarks, userID)	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) DeleteBookmark(userID, id string) error {}	return out, r.saveLocked()	out := r.upsertBookmarkLocked(userID, item)	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) UpsertBookmark(userID string, item domain.Bookmark) (domain.Bookmark, error) {}	return r.saveLocked()	bucket[id] = item	item.UpdatedAt = now	item.DeletedAt = &now	item.UserID = userID	now := time.Now().UTC()	}		return service.ErrNotFound	if !ok {	item, ok := bucket[id]	bucket := ensureBucket(r.data.Highlights, userID)	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) DeleteHighlight(userID, id string) error {}	return out, r.saveLocked()	out := r.upsertHighlightLocked(userID, item)	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) UpsertHighlight(userID string, item domain.Highlight) (domain.Highlight, error) {}	return r.saveLocked()	bucket[id] = item	item.UpdatedAt = now	item.DeletedAt = &now	item.UserID = userID	now := time.Now().UTC()	}		return service.ErrNotFound	if !ok {	item, ok := bucket[id]	bucket := ensureBucket(r.data.Notes, userID)	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) DeleteNote(userID, id string) error {}	return out, r.saveLocked()	out := r.upsertNoteLocked(userID, note)	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) UpsertNote(userID string, note domain.Note) (domain.Note, error) {}	return r.snapshotLocked(user), nil	}		return domain.SyncSnapshot{}, err	if err := r.saveLocked(); err != nil {	}		r.upsertReadingPositionLocked(userID, item)	for _, item := range push.ReadingPositions {	}		r.upsertBookmarkLocked(userID, item)	for _, item := range push.Bookmarks {	}		r.upsertHighlightLocked(userID, item)	for _, item := range push.Highlights {	}		r.upsertNoteLocked(userID, item)	for _, item := range push.Notes {	}		return domain.SyncSnapshot{}, service.ErrNotFound	if !ok {	user, ok := r.data.Users[userID]	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) ApplySync(userID string, push domain.SyncPushRequest) (domain.SyncSnapshot, error) {}	return r.snapshotLocked(user), nil	}		return domain.SyncSnapshot{}, service.ErrNotFound	if !ok {	user, ok := r.data.Users[userID]	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) Snapshot(userID string) (domain.SyncSnapshot, error) {}	return &copy, nil	copy := user	}		return nil, service.ErrNotFound	if !ok {	user, ok := r.data.Users[id]	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) GetUserByID(id string) (*domain.User, error) {}	return &copy, nil	copy := user	}		return nil, service.ErrNotFound	if !ok {	user, ok := r.findUserByEmailLocked(strings.ToLower(strings.TrimSpace(email)))	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) FindUserByEmail(email string) (*domain.User, error) {}	return user, r.saveLocked()	r.data.Users[user.ID] = user	}		return domain.User{}, service.ErrEmailTaken	if _, ok := r.findUserByEmailLocked(user.Email); ok {	defer r.mu.Unlock()	r.mu.Lock()func (r *Repository) CreateUser(user domain.User) (domain.User, error) {}	return r, nil	}		return nil, err	if err := r.load(); err != nil {	r := &Repository{path: path, data: newState()}func New(path string) (*Repository, error) {}	ReadingPositions map[string]map[string]domain.ReadingPosition `json:"readingPositions"`	Bookmarks        map[string]map[string]domain.Bookmark        `json:"bookmarks"`	Highlights       map[string]map[string]domain.Highlight       `json:"highlights"`	Notes            map[string]map[string]domain.Note            `json:"notes"`	Users            map[string]domain.User                       `json:"users"`type state struct {}	data state	path string	mu   sync.Mutextype Repository struct {)